apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gyenoch/fullstackbank_backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: APP_PORT
              value: "3001"
            - name: JWT_SECRET
              value: "jwt_secret"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "123456"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
          livenessProbe:
            exec:
              command:
                - lsof
                - "-t"
                - "-i:3001"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - lsof
                - "-t"
                - "-i:3001"
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
